const CLAUSULAS_OBRIGATORIAS_CONTRATO = [
    'CLAUSULA 1 - DO OBJETO',
    '1.1 Locacao de veiculos pertencentes a frota do LOCADOR, destinados ao uso comercial ou particular, conforme autorizacao expressa.',
    '1.2 Os veiculos serao especificados em anexos operacionais (OS/Checklist), com descricao de modelo, placa, quilometragem inicial, acessorios e condicoes gerais.',
    '',
    'CLAUSULA 2 - DA NATUREZA DA PLATAFORMA, LIMITAÇÃO DE RESPONSABILIDADE E FUNDAMENTAÇÃO LEGAL',
    '2.1 A Plataforma atua exclusivamente como intermediadora digital, fornecendo infraestrutura tecnologica para aproximacao entre LOCADORES e LOCATÁRIOS, não integrando a relação jurídica de locação de veículos firmada entre as partes, nem assumindo qualquer posição de fornecedora direta do serviço de locação.',
    '2.2 Nos termos do Marco Civil da Internet, especialmente quanto ao regime de responsabilidade de provedores de aplicações, a Plataforma não poderá ser responsabilizada por conteúdos, informações, anúncios ou condutas praticadas por terceiros usuários, limitando-se a disponibilizar ambiente digital de intermediação, sem ingerência sobre as transações realizadas.',
    '2.3 A Plataforma não possui, administra, inspeciona, garante ou detém posse sobre os veículos anunciados, sendo de responsabilidade exclusiva do LOCADOR:',
    '- I – a veracidade e exatidão das informações disponibilizadas;',
    '- II – a regularidade jurídica e documental do veículo;',
    '- III – as condições de uso, conservação e segurança;',
    '- IV – o cumprimento integral das normas legais e regulatórias aplicáveis.',
    '2.4 O LOCATÁRIO reconhece que a contratação é firmada diretamente com o LOCADOR, sendo responsável por avaliar previamente as condições do veículo, a idoneidade do LOCADOR e os termos da locação, assumindo os riscos inerentes à contratação.',
    '2.5 Nos termos do Código de Defesa do Consumidor, a Plataforma não se caracteriza como fornecedora do serviço de locação de veículos, atuando apenas como provedora de tecnologia e intermediação, não se aplicando, portanto, responsabilidade objetiva por vícios ou defeitos do serviço prestado pelo LOCADOR, ressalvadas as hipóteses legais expressamente previstas.',
    '2.6 A Plataforma não se responsabiliza, em nenhuma hipótese, por:',
    '- I – danos diretos, indiretos, incidentais, especiais ou lucros cessantes decorrentes da locação;',
    '- II – vícios, defeitos ou falhas mecânicas dos veículos;',
    '- III – inadimplemento contratual de quaisquer das partes;',
    '- IV – acidentes, multas, infrações ou danos ocorridos durante a locação;',
    '- V – condutas ilícitas praticadas por usuários.',
    '2.7 Qualquer responsabilidade da Plataforma, quando legalmente reconhecida, ficará limitada ao valor efetivamente pago pelo usuário à Plataforma a título de taxa de intermediação nos últimos 12 (doze) meses, excluindo-se indenizações por lucros cessantes e danos indiretos.',
    '2.8 Eventuais disputas oriundas da locação deverão ser resolvidas exclusivamente entre LOCADOR e LOCATÁRIO, afastando-se a responsabilidade solidária ou subsidiária da Plataforma, salvo determinação judicial em sentido diverso.',
    '2.9 Ao aderirem à Plataforma, LOCADOR e LOCATÁRIO declaram ciência inequívoca da natureza jurídica de intermediação tecnológica aqui estabelecida, concordando integralmente com a limitação de responsabilidade prevista nesta cláusula.',
    '',
    'CLAUSULA 3 - DO PRAZO',
    '3.1 O prazo de locacao sera definido por ordem de servico vinculada a este contrato, com inicio e termino registrados digitalmente.',
    '3.2 A renovacao podera ocorrer mediante aceite digital, condicionada a analise de credito e disponibilidade do veiculo.',
    '',
    'CLAUSULA 4 - VALORES E COBRANCA',
    '4.1 Valores definidos por diaria/mensalidade conforme tabela vigente:',
    '- Diaria: R$ 120,00',
    '- Mensalidade (30 dias): R$ 2.990,00',
    '4.2 Caucao obrigatoria no valor de R$ 1.500,00, a ser devolvida apos vistoria final sem ressalvas.',
    '4.3 Em caso de atraso no pagamento, incidirao juros de 1% ao mes e multa de 2% sobre o valor devido.',
    '',
    'CLAUSULA 5 - USO DO VEICULO',
    '5.1 Permitido uso em aplicativos (Uber/99), desde que autorizado formalmente no ato da locacao.',
    '5.2 Proibido uso ilicito, transporte de cargas perigosas, sublocacao ou circulacao fora dos limites geograficos do Estado de Sao Paulo sem autorizacao previa.',
    '',
    'CLAUSULA 6 - RESPONSABILIDADE',
    '6.1 O LOCATARIO responde por danos, perdas, furtos, roubos e prejuizos causados a terceiros, salvo cobertura expressa da apolice de seguro.',
    '6.2 Deve comunicar incidentes imediatamente a LOCADORA e registrar boletim de ocorrencia quando aplicavel.',
    '',
    'CLAUSULA 7 - SEGURO',
    '7.1 Cobertura conforme apolice vigente da Seguradora Protege Auto S.A., n 2024.001234-5.',
    '7.2 Franquia de R$ 3.000,00 para sinistros, sob responsabilidade do LOCATARIO.',
    '',
    'CLAUSULA 8 - MULTAS',
    '8.1 Infracoes de transito serao transferidas ao condutor infrator via sistema digital do DETRAN.',
    '8.2 Taxa administrativa de R$ 50,00 por notificacao de infracao recebida.',
    '',
    'CLAUSULA 9 - FLUXO OPERACIONAL',
    '9.1 RETIRADA: assinatura digital + checklist inicial com fotos georreferenciadas.',
    '9.2 USO: monitoramento de quilometragem, telemetria e condicoes de uso.',
    '9.3 DEVOLUCAO: vistoria final comparativa + aceite digital.',
    '9.4 REGISTROS: todas as etapas serao armazenadas eletronicamente por no minimo 5 anos.',
    '',
    'CLAUSULA 10 - VISTORIA DIGITAL',
    '10.1 Checklists realizados via aplicativo FrotaCheck.',
    '10.2 Evidencias fotograficas obrigatorias em todas as etapas.',
    '10.3 Divergencias identificadas na devolucao geram cobranca automatica no cartao cadastrado.',
    '',
    'CLAUSULA 11 - ESCALA (FROTA)',
    '11.1 Este contrato cobre multiplos veiculos, podendo ser adicionados conforme necessidade do LOCATARIO.',
    '11.2 Cada locacao sera vinculada a um registro operacional unico, com controle de datas, condutor e veiculo.',
    '11.3 Gestao centralizada de clientes e veiculos via sistema ERP da LOCADORA.',
    '',
    'CLAUSULA 12 - LGPD',
    '12.1 Os dados pessoais fornecidos serao tratados conforme a Lei n 13.709/2018 (LGPD), exclusivamente para execucao do contrato.',
    '',
    'CLAUSULA 13 - RESCISAO',
    '13.1 Multa de 30% sobre o valor restante do contrato em caso de rescisao antecipada pelo LOCATARIO.',
    '13.2 Rescisao imediata por descumprimento de quaisquer clausulas contratuais ou uso indevido do veiculo.',
    '',
    'CLAUSULA 14 - FORO',
    '14.1 Fica eleito o foro da comarca de Campinas/SP para dirimir quaisquer duvidas ou litigios decorrentes deste contrato.',
];

function buildContractClauses(extraClauses = []) {
    const extras = Array.isArray(extraClauses) ? extraClauses.filter(Boolean) : [];
    if (extras.length === 0) return [...CLAUSULAS_OBRIGATORIAS_CONTRATO];

    return [
        ...CLAUSULAS_OBRIGATORIAS_CONTRATO,
        '',
        'CLAUSULAS COMPLEMENTARES (DOCUMENTO BASE):',
        ...extras,
    ];
}

module.exports = {
    CLAUSULAS_OBRIGATORIAS_CONTRATO,
    buildContractClauses,
};
